// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Medpersonal struct {
	ID            int32
	Lastname      string
	Address       string
	Taxpercentage string
}

type Operationtype struct {
	ID        int32
	Name      string
	Basepoint string
	Stock     int32
	Cost      string
}

type Workactivity struct {
	Contract      int32
	Date          string
	Medpersonalid int32
	Workplaceid   int32
	Operationid   int32
	Quantity      int32
	Payment       string
}

type Workplace struct {
	ID                    int32
	Institution           string
	Address               string
	Localbudgetpercentage string
}
