// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: OperationTypes.sql

package database

import (
	"context"
)

const createOperationTypes = `-- name: CreateOperationTypes :one
INSERT INTO OperationTypes (ID, Name, Basepoint, Stock, Cost)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, basepoint, stock, cost
`

type CreateOperationTypesParams struct {
	ID        int32
	Name      string
	Basepoint string
	Stock     int32
	Cost      string
}

func (q *Queries) CreateOperationTypes(ctx context.Context, arg CreateOperationTypesParams) (Operationtype, error) {
	row := q.db.QueryRowContext(ctx, createOperationTypes,
		arg.ID,
		arg.Name,
		arg.Basepoint,
		arg.Stock,
		arg.Cost,
	)
	var i Operationtype
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Basepoint,
		&i.Stock,
		&i.Cost,
	)
	return i, err
}
