// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: WorkActivity.sql

package database

import (
	"context"
)

const createWorkActivity = `-- name: CreateWorkActivity :one
INSERT INTO WorkActivity (Contract, Date, MedpersonalID, WorkplaceID, OperationID, Quantity, Payment)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING contract, date, medpersonalid, workplaceid, operationid, quantity, payment
`

type CreateWorkActivityParams struct {
	Contract      int32
	Date          string
	Medpersonalid int32
	Workplaceid   int32
	Operationid   int32
	Quantity      int32
	Payment       string
}

func (q *Queries) CreateWorkActivity(ctx context.Context, arg CreateWorkActivityParams) (Workactivity, error) {
	row := q.db.QueryRowContext(ctx, createWorkActivity,
		arg.Contract,
		arg.Date,
		arg.Medpersonalid,
		arg.Workplaceid,
		arg.Operationid,
		arg.Quantity,
		arg.Payment,
	)
	var i Workactivity
	err := row.Scan(
		&i.Contract,
		&i.Date,
		&i.Medpersonalid,
		&i.Workplaceid,
		&i.Operationid,
		&i.Quantity,
		&i.Payment,
	)
	return i, err
}
